# Generated by Django 6.1 on 2026-08-18 12:14

from django.db import migrations


DEFAULT_CATEGORIES = [
    ("Salary", "income"),
    ("Freelance", "income"),
    ("Gifts", "income"),

    ("Groceries", "expense"),
    ("Transport", "expense"),
    ("Utilities", "expense"),
    ("Rent", "expense"),
    ("Entertainment", "expense"),
    ("Health", "expense"),
    ("Other", "expense"),
]


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("finance", "Category")
    for name, category_type in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(
            name=name,
            category_type=category_type,
            owner=None,
        )


def remove_default_categories(apps, schema_editor):
    Category = apps.get_model("finance", "Category")
    Category.objects.filter(
        owner__isnull=True,
        name__in=[name for name, _ in DEFAULT_CATEGORIES],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]